# Generated by Django 4.2.5 on 2023-11-02 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_remove_car_id_alter_car_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
