# Generated by Django 4.2.5 on 2023-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/88/8m/8d/'),
        ),
    ]
