# Generated by Django 4.2.5 on 2023-10-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_title_news_tittle_alter_category_tittle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='tittle',
            new_name='title',
        ),
    ]
